Run Command and Configuring format
concordion/concordion-timing-extension pull request #3
Opened 2016-09-22 03:19 UTC by zyphrus

2016-09-25 09:50 UTC, nigelcharman requested changes
I've made a few comments on the PR. I'm still considering the best solution for the run command, but can't merge that until it's working. If you can make a smaller PR without the run command I could merge that in.

2016-09-25 09:50 UTC, nigelcharman commented on src/main/java/org/concordion/ext/timing/TimerExtension.java
> +     */
Just wondering if we should have plurals too? 
Or even allow people to pass in their own TimeFormatter implementation? (we'd need to create an interface for this)

2016-09-25 09:50 UTC, nigelcharman commented on src/main/resources/org/concordion/ext/timing/js/toggle.js
> +                toggleButton.style.backgroundColor = "#F5F9FD";
Just wondering if we can remove the console.log() line a few lines up from this one. I assume it's for debug that's no longer needed?

2016-09-25 09:50 UTC, nigelcharman commented on src/test/java/org/concordion/ext/timing/junit/footer/TimerSpecificationListenerTests.java
>  }
For clarity, I'd extract the common code from the 3 test methods into private method(s). It would then be easier to see what the difference is between each test, and what stays the same.

(I don't always suggest reducing duplication in tests. For me . clarity of test trumps the DRY principle. But in this case, there's so much duplication I'd argue it's much clearer if you extract the duplication).

2016-09-25 09:50 UTC, nigelcharman commented on build.gradle
>              name 'Nigel Charman'
Please remove me :)

2016-09-25 09:50 UTC, nigelcharman commented on src/main/java/org/concordion/ext/timing/footer/TimeFormatter.java
> +
Hey, I'm not sure why the package name for this is "footer". How about renaming it?

2016-10-05 07:43 UTC, nigelcharman reviewed
Looking good, just one small comment

2016-10-05 07:43 UTC, nigelcharman commented on src/main/java/org/concordion/ext/timing/TimerExtension.java
> +    public ConcordionExtension withTimeFormat(TimeFormatter timeFormat){
Maybe rename to withTimeFormat**ter**?

2016-10-05 20:06 UTC, zyphrus commented on src/main/java/org/concordion/ext/timing/TimerExtension.java
> +    public ConcordionExtension withTimeFormat(TimeFormatter timeFormat){
Good point, has been renamed in the latest commit

2016-10-05 20:51 UTC, nigelcharman approved these changes

2016-10-05 20:51 UTC, merged